// Kheelan product copy — confident, product-first (not family-app tone).

export const copy = {
  connecting: {
    title: "Getting your room ready",
    server: "Connecting to game server…",
    waking: "Waking up server — the first launch after idle can take up to a minute.",
    slow: "Still connecting…",
    creating: "Creating your room…",
    restoring: "Restoring your game…",
    verySlow: "Almost there — free servers are slow to wake the first time.",
  },
  lobby: {
    playersLabel: "Players",
    playerCount: (n) => `${n} ${n === 1 ? "player" : "players"} in the lobby`,
    recommendedMax: (n, max) => `${n} / ${max} recommended max`,
    overRecommendedMax:
      "Over the recommended max — lock the lobby if you're done adding players.",
    waiting: "Waiting for players",
    waitingHint: "Share the PIN or QR — they'll appear here",
    emptyCta: "Need at least one player to start",
    start: "Start session",
    pinLabel: "Game PIN:",
    joinAt: "Join at",
    joinOr: "or scan the",
    joinQr: "QR code",
    scan: "Scan to join",
    modeSolo: "Individual scoring",
    modeTeams: "Team mode",
    lockedTitle: "Locked — no new players can join",
    unlockedTitle: "Unlocked — players can join with the PIN",
    lockedStatus: "Lobby locked — no new joins",
    lockedJoin: "The host locked the room. Ask them to unlock it so you can join.",
    kicked: "The host removed you from the lobby.",
    copyPin: "Copy the game PIN",
    copiedPin: "PIN copied!",
    leaveLobby: "Leave lobby",
    leaveLobbyTitle: "Close lobby and return to dashboard",
  },
  countdown: {
    label: "Get ready",
    go: "GO!",
  },
  host: {
    recovered: "You're back — room restored.",
    playersBack: "Host is back online.",
    hostAway: "Host stepped away — hang tight.",
    endConfirm: "End session",
    endSessionTitle: "End game for everyone and return to dashboard",
    pause: "Pause round",
    resume: "Resume round",
    skipResults: "Show results now",
    skipReveal: "Skip to highlight",
    showStandings: "Scoreboard",
    nextQuestion: "Next question",
    finalResults: "Final results",
    pacing: {
      label: "Show pace",
      quick: "Quick",
      normal: "Normal",
      cinematic: "Cinematic",
      quickHint: "Snappy reveals — keep momentum high.",
      normalHint: "Balanced pacing for most rooms.",
      cinematicHint: "Let each beat land.",
    },
  },
  settings: {
    done: "Done",
    title: "Settings",
    appearance: "Appearance",
    themeLabel: "Light or dark",
    themeHint: "Sun = day · Moon = night. Tap to switch.",
    lobbyMusicHint: "Lofi lobby groove while you wait.",
  },
  player: {
    joined: "You're in",
    lobbyWait: "Watch the host screen — starting soon.",
    lobbyCrowd: (n) => (n === 1 ? "You're the first player here" : `${n} players in the room`),
    disconnected: "Connection lost — reconnecting…",
    pinStep: "Enter the 6-digit code from the host screen.",
    profileCta: "Join session",
    editLook: "Edit your look",
    editLookHint: "Change your avatar anytime — the host screen updates too.",
    editLookCta: "Change look",
    saveLook: "Save look",
    savingLook: "Saving…",
    joining: "Joining…",
    reconnect: "Back online — your score is saved.",
    paused: "Session paused",
    revealSoon: "Results coming up…",
    result: {
      correct: "Correct",
      partial: "So close!",
      wrong: "Not this time",
      timeout: "Time ran out",
      points: (n, mult) =>
        n > 0 ? `+${n.toLocaleString()} pts${mult === 2 ? " · 2×" : ""}` : "0 pts",
      rank: (r, total) => `#${r} of ${total}`,
      correctWas: "Correct answer",
      watchScreen: "Watch the host screen for the reveal.",
    },
    standings: "Your rank",
    onPodium: "Top three!",
    onPodiumTeaser: "Your exact spot is on the host screen.",
    final: "You placed",
    gameOver: "Session ended",
    playAgain: "Join another game",
  },
  reveal: {
    nobody: "No correct answers",
    standingsCta: "See the scoreboard",
    doublePoints: "2× points round",
  },
  standings: {
    title: "Scoreboard",
    subtitle: (i, total) => `After question ${i + 1} of ${total}`,
    teamRace: "Team standings",
    stillAnyone: "Still anyone's game",
  },
  final: {
    title: "Final scores",
    recapCta: "Session recap",
    recapHint: "Screenshot this for your team.",
    podiumRest: "Everyone else",
    topContributors: "Top contributors",
  },
  social: {
    fastest: "Fastest correct",
    clutch: "Clutch pick",
    comeback: "Biggest climb",
    confidentWrong: "Fast miss",
  },
  ended: {
    title: "Session over",
    hostEnded: "The host ended the session.",
    hostDisconnect: "Host connection dropped.",
  },
  landing: {
    headline: "Stop lecturing to a room full of phones.",
    subhead: "Host a live game show in 60 seconds. You run the big screen — everyone plays from their phone. No app for players.",
    hostCta: "Host free →",
    hostCtaSub: "No credit card · players join free on their phones",
    trustLine: "Free to host during beta · players never pay",
    socialProof: "Teachers, team leads, and event hosts — not another slide deck",
    socialStat: "847 sessions hosted this week",
    heroBadge: "Free to host · beta",
    demoLabel: "Try it — one question, see the vibe",
    demoCorrect: "Fast fingers win in the real game too. That was 920 pts.",
    demoWrong: "Mars. In a live room the whole class sees the reveal on your screen.",
    demoDone: "That's the loop. Your room. Your questions. Host free — takes 60 seconds.",
    demoCta: "Host free →",
    demoPopupTitle: "You're already better than most hosts.",
    demoPopupWrongTitle: "Wrong — but now they're watching.",
    demoPopupBody: "Imagine 30 phones doing this at once while you control the big screen. Host your first room free.",
    demoTryAgain: "One more try",
    joinTitle: "Got a PIN? Jump in.",
    joinCta: "Join the room →",
    pricing: {
      eyebrow: "Pricing",
      title: "One plan. No BS.",
      subtitle: "Players join free. You pay less than Kahoot — or nothing while we're in beta.",
      compareLine: "",
      playerNote: "Players never need an account or a credit card.",
      plans: [
        {
          id: "pro",
          name: "Kheelan Pro",
          tagline: "Unlimited games. Unlimited players. No app for anyone.",
          badge: "Early access",
          price: "$0",
          period: "to host now",
          priceSub: "Then $3.99/mo when billing goes live",
          vs: {
            themLabel: "Kahoot Gold",
            themPrice: "~$9/mo",
            usLabel: "Kheelan Pro",
            usPrice: "$3.99/mo",
          },
          trial: "No credit card · cancel anytime",
          features: [
            "Unlimited live games",
            "Unlimited players on one PIN",
            "Custom quizzes + full editor",
            "Team mode & speed scoring",
            "Session recap & share cards",
          ],
          cta: "Host free →",
        },
      ],
    },
    benefits: {
      eyebrow: "The problem",
      title: "Sound familiar?",
      items: [
        {
          emoji: "📊",
          oldWay: "The old way",
          title: "Death by PowerPoint",
          body: "You talk for 40 minutes. They scroll. Nothing sticks. You blame the WiFi.",
        },
        {
          emoji: "⏱️",
          oldWay: "The old way",
          title: "45-minute icebreakers",
          body: "You spent lunch planning an activity. They forgot it by question two.",
        },
        {
          emoji: "😶",
          oldWay: "The old way",
          title: "Cricket chirping",
          body: "\"Any questions?\" Silence. Polls nobody answers. Games nobody downloaded.",
        },
      ],
    },
    quotes: {
      eyebrow: "Don't take our word for it",
      title: "Rooms that actually woke up",
      items: [
        {
          text: "200-person lecture. Phones went down in 30 seconds. I've never seen that.",
          name: "Dr. Patel",
          role: "Biology · UT Austin",
          avatar: { base: "owl", accessory: "shades", color: "#3b82f6" },
        },
        {
          text: "Setup took 47 seconds. I literally timed it. Our standup is actually fun now.",
          name: "Marie L.",
          role: "Eng manager · Paris",
          avatar: { base: "fox", accessory: "crown", color: "#f43f5e" },
        },
        {
          text: "No app install = no IT ticket. My students joined before I finished explaining how.",
          name: "Fatima A.",
          role: "8th grade · Abu Dhabi",
          avatar: { base: "bunny", accessory: "wizard", color: "#7c3aed" },
        },
      ],
    },
    finalCta: {
      eyebrow: "Last call",
      title: "Your next room could be awake in 60 seconds.",
      body: "Host free — your room can be live in 60 seconds. Players still join with a PIN, no app.",
      cta: "Host free →",
      footnote: "Free during beta · Pro pricing coming soon",
    },
    faq: {
      title: "Fine, here's the FAQ.",
      subtitle: "Questions you're thinking",
      cta: "Host free →",
      items: [
        {
          id: "pricing",
          q: "How much does it cost?",
          a: "Hosting is free during beta. Pro will be $3.99/mo when billing launches — unlimited games, unlimited players, full editor. Players always join free.",
        },
        {
          id: "kahoot",
          q: "Is this cheaper than Kahoot?",
          a: "Yes — a lot. Kahoot Gold is ~$9/mo, usually billed yearly upfront. Kheelan Pro is $3.99/mo, cancel anytime. Players join free.",
        },
        {
          id: "players",
          q: "Do players have to pay?",
          a: "Never. Players join free with a PIN in their browser. Hosting is free during beta.",
        },
        {
          id: "app",
          q: "Do players need to download something?",
          a: "Nope. PIN in the browser. Works on the phone they already have in their hand. That's the point.",
        },
        {
          id: "join",
          q: "How fast can people join?",
          a: "Share the PIN or QR. They pick a nickname and avatar. Most rooms are live in under 90 seconds.",
        },
        {
          id: "trial",
          q: "When will paid plans launch?",
          a: "Pro will be $3.99/mo with a free trial when billing goes live. Until then, host as much as you want — no credit card.",
        },
      ],
    },
    footer: "Built for rooms that deserve better than another slide.",
  },
  share: {
    copySuccess: "Copied!",
    copyFail: "Couldn't copy — select and share manually.",
    copyTemplate: (rank, domain) => `${domain} — I placed #${rank} in a live quiz`,
    hostCta: "Host a game →",
    statPodium: "Top three finish",
    statMid: "Solid run — room was competitive",
    statClutch: "Clutched a spot on the board",
    statLearning: "Every round is practice for the rematch",
  },
};

export function funStatTitle(key) {
  const map = {
    fastest_finger: copy.social.fastest,
    confident_wrong: copy.social.confidentWrong,
    biggest_comeback: copy.social.comeback,
    steady_climb: copy.standings.stillAnyone,
  };
  return map[key] || key;
}
